tuexperto/tuexperto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.urls import reverse_lazy
from django.conf.urls import handler404, handler500
from django.contrib.auth.views import (LoginView,
                                       LogoutView,)

from accounts.views import (ProfileView,)

from .views import (HomeView, register_view, activate, ContactFormView)
from blog.views import (PostView,
                        CategoryView,
                        SubCategoryView,
                        UserPostListView,
                        PostCreateView,
                        PostUpdateView,
                        PostDeleteView,
                        SearchView
                        )
from courses.views import (UserCourseListView,
                           UserCourseDetailView,
                           CoursePostCreateView,
                           CoursePostView,
                           CourseCreateView)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name="home"),
    path('search/', SearchView.as_view(), name="search"),
    path('contact/', ContactFormView.as_view(), name="contact"),

    path('topic/<slug:slug>/', CategoryView.as_view(), name="category"),
    path('topic/<slug:category>/<slug:slug>',
         SubCategoryView.as_view(), name="subcategory"),
    path('<slug:slug>', PostView.as_view(), name="post"),

    path('courses/<slug:course>/<slug:slug>', CoursePostView.as_view(), name="course_post"),

    path('profile/<slug:username>/', ProfileView.as_view(), name='profile'),

    # Auth System
    path('account/signin/', LoginView.as_view(template_name='auth/login.html',
                                              redirect_authenticated_user=True,
                                              extra_context={'title_page': 'Sign in',
                                                             'breadcrumb': [(reverse_lazy('home'), 'Inicio'), 
                                                             ('', 'Iniciar Sesión')]}), name='signin'),

    path('account/logout/', LogoutView.as_view(), name='logout'),
    path('account/signup/', register_view, name='signup'),

    path('account/courses/', UserCourseListView.as_view(), name='user_courses'),
    path('account/courses/<slug:slug>/', UserCourseDetailView.as_view(), name='user_courses_detail'),
    path('account/courses/<slug:course>/new', CoursePostCreateView.as_view(), name='user_courses_detail_new'),
    path('account/courses/new', CourseCreateView.as_view(), name='user_courses_new'),

    path('account/<slug:pt>/', UserPostListView.as_view(), name='user_post'),
    path('account/<slug:pt>/new', PostCreateView.as_view(), name='user_post_new'),
    path('account/<slug:pt>/<slug:slug>/edit',
         PostUpdateView.as_view(), name='user_post_edit'),
    path('account/<slug:pt>/<slug:slug>/delete',
         PostDeleteView.as_view(), name='user_post_delete'),


    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('select2/', include('django_select2.urls')),
    path('activate/<str:uidb64>/<str:token>', activate, name='activate'),

    # Api
    path('api/blog/', include('blog.api.urls')),
    path('api/account/', include('accounts.api.urls')),

]
if settings.DEBUG:
    # static = Funcion auxiliar para devolver un patron de URL para servir archivos en modo debug
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

handler404 = 'tuexperto.views.error_404'

tuexperto/blog/models.py
from ckeditor.fields import RichTextField
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from meta.models import ModelMeta
from utils.generators import (
    unique_slug_generator, unique_categories_slug_generator)
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils.text import slugify

from django.utils.encoding import python_2_unicode_compatible
from hitcount.models import HitCountMixin, HitCount
from django.contrib.contenttypes.fields import GenericRelation


def post_directory_path(instance, filename):
    filename = "{0}.jpg".format(slugify(instance.title))
    return '{0}/{1}'.format(slugify(instance.title), filename)


class Category(ModelMeta, models.Model):

    category = models.CharField(max_length=50)

    description = models.CharField(max_length=200, blank=True, null=True)

    slug = models.SlugField(blank=True, null=True)

    _metadata = {
        'title': 'title',
        'description': 'description',
        'extra_props': 'extra_props',
        'extra_custom_props': 'custom_props'
    }

    created_at = models.DateTimeField(auto_now_add=True)

    @property
    def title(self):
        return self.category.capitalize()

    def extra_props(self):
        return {'viewport': 'width=device-width, initial-scale=1.0, minimum-scale=1.0'}

    def custom_props(self):
        return [('http-equiv', 'Content-Type', 'text/html; charset=UTF-8')]

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.category


class SubCategory(ModelMeta, models.Model):

    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    subcategory = models.CharField(max_length=50)

    description = models.CharField(max_length=200, blank=True, null=True)

    slug = models.SlugField(blank=True, null=True)

    _metadata = {
        'title': 'title',
        'description': 'description',
        'extra_props': 'extra_props',
        'extra_custom_props': 'custom_props'
    }

    created_at = models.DateTimeField(auto_now_add=True)

    @property
    def title(self):
        return self.subcategory.capitalize()

    def extra_props(self):
        return {'viewport': 'width=device-width, initial-scale=1.0, minimum-scale=1.0'}

    def custom_props(self):
        return [('http-equiv', 'Content-Type', 'text/html; charset=UTF-8')]

    class Meta:
        verbose_name = "Subcategory"
        verbose_name_plural = "Subcategories"

    def __str__(self):
        return self.title


class Tag(models.Model):

    tag = models.CharField(max_length=50, unique=True)

    class Meta:
        verbose_name = "Tag"
        verbose_name_plural = "Tags"

    def __str__(self):
        return self.tag


class Post(ModelMeta, models.Model):

    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    description = models.CharField(max_length=200)

    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, blank=True, null=True)
    subcategory = models.ForeignKey(
        SubCategory, on_delete=models.CASCADE, blank=True, null=True)

    title = models.CharField(max_length=150, unique=True)
    slug = models.SlugField(unique=True, blank=True, null=True)

    content = RichTextUploadingField()

    image = models.ImageField(upload_to=post_directory_path)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    post_type = models.CharField(max_length=2, choices=(
        ('pg', 'page'), ('pt', 'post'), ('co', 'course')), default='pt')

    tags = models.ManyToManyField(Tag)

    is_active = models.BooleanField(default=True)

    show_in_navbar = models.BooleanField(default=False)

    _metadata = {
        'title': 'title',
        'description': 'description',
        'keywords': 'get_kw',
        'extra_props': 'extra_props',
        'extra_custom_props': 'custom_props'
    }

    def get_kw(self):
        tags = self.tags.all()
        if tags.count() > 0:
            return [x.tag for x in tags]

        return []

    def extra_props(self):
        return {'viewport': 'width=device-width, initial-scale=1.0, minimum-scale=1.0'}

    def custom_props(self):
        return [('http-equiv', 'Content-Type', 'text/html; charset=UTF-8')]

    class Meta:
        verbose_name = "Post"
        verbose_name_plural = "Posts"

    def __str__(self):
        return self.title

@receiver(post_save, sender=Category)
def post_save_categories(sender, instance, created, **kwargs):
    if not instance.slug:
        instance.slug = "{0}".format(unique_slug_generator(instance))
        instance.save()


@receiver(post_save, sender=SubCategory)
def post_save_subcategories(sender, instance, created, **kwargs):
    if not instance.slug:
        instance.slug = "{0}".format(unique_slug_generator(instance))
        instance.save()


@receiver(post_save, sender=Post)
def post_save_post(sender, instance, created, **kwargs):
    if not instance.slug:
        instance.slug = "{0}".format(unique_slug_generator(instance))
        instance.save()

tuexperto/templates/components/base.html
{% load static %}
{% load humanize %}
{% load meta %}
<!DOCTYPE html>
<html class="no-js" lang="es">
	<head {% meta_namespaces %}> 

		{% include "meta/meta.html" %}
		<!-- Bootstrap Core CSS -->
		<link rel="stylesheet" href="{% static "assets/plugins/bootstrap/css/bootstrap.min.css" %}">
		
		<!-- Bootstrap Select Option css -->
		<link rel="stylesheet" href="{% static "assets/plugins/bootstrap/css/bootstrap-select.min.css" %}">
		
	    <!-- Icons -->
	    <link href="{% static "assets/plugins/icons/css/icons.css" %}" rel="stylesheet">
	    
	    <!-- Animate -->
	    <link href="{% static "assets/plugins/animate/animate.css" %}" rel="stylesheet">
	    
	    <!-- Bootsnav -->
	    <link href="{% static "assets/plugins/bootstrap/css/bootsnav.css" %}" rel="stylesheet">
		
		<!-- Nice Select Option css -->
		<link rel="stylesheet" href="{% static "assets/plugins/nice-select/css/nice-select.css" %}">
		
		<!-- Aos Css -->
	    <link href="{% static "assets/plugins/aos-master/aos.css" %}" rel="stylesheet">

		<!-- Slick Slider -->
	    <link href="{% static "assets/plugins/slick-slider/slick.css" %}" rel="stylesheet">	
	    
	    <!-- Custom style -->
	    <link href="{% static "assets/css/style.css" %}" rel="stylesheet">
		<link href="{% static "assets/css/responsiveness.css" %}" rel="stylesheet">
		
		<!-- Custom Color -->
	    <link href="{% static "assets/css/skin/default.css" %}" rel="stylesheet">
		{% block style %}
			
		{% endblock style %}
	</head>
	
	<body>
		
		{% include "components/navbar.html" %}
		
		{% block content %}
			{% endblock content %}
			<!-- ================= footer start ========================= -->
			<footer class="footer dark-bg">
				<div class="container">
					
					<!-- Row Start -->
					<div class="row">

						<div class="col-md-7 col-sm-7">
							<div class="row">
								<div class="col-md-4 col-sm-6">
									<h4>Sitio</h4>
									<ul>
										{% for page in pages %}
										<li><a href="{% url 'post' slug=page.slug %}">{{page.title|capfirst}}</a></li>
										{% endfor %}
										{% if user.is_authenticated != True %}
										<li><a href="{% url 'signin' %}">Acceder</a></li>
										<li><a href="{% url 'signup' %}">Registrarse</a></li>
										{% endif %}
									</ul>
								</div>
								<div class="col-md-4 col-sm-6">
									<h4>Categorías</h4>
									<ul>
										{% if categories %}
											{% for category in categories %}
												<li><a href="{% url 'category' category.slug %}">{{category.category|title}}</a></li>
											{% endfor %}
										{% endif %}
									</ul>
								</div>
								<div class="col-md-4 col-sm-6">
									<h4>últimas Entradas</h4>
									<ul>
										{% if last_post %}
										{% for post in last_post %}
												<li><a href="{% url 'post' post.slug %}">{{post.title|capfirst}}</a></li>
											{% endfor %}
										{% endif %}
									</ul>
								</div>
							</div>
						</div>
						
						<div class="col-md-5 col-sm-5">
							<h4>Suscríbete!</h4>
							<!-- Newsletter -->
							<form id="subscriberForm" method="post">
								<div class="input-group">
									<input type="text" name="email" id="email" class="form-control" placeholder="Enter Email">
									<span class="input-group-btn">
										<button type="submit" class="btn btn-default"><i class="fa fa-location-arrow font-20"></i></button>
									</span>
								</div>
							</form>
							
							<!-- Social Box -->
							<div class="f-social-box">
								<ul>
									<li><a href="#"><i class="fa fa-facebook facebook-cl"></i></a></li>
									<li><a href="#"><i class="fa fa-twitter twitter-cl"></i></a></li>
									<li><a href="#"><i class="fa fa-instagram instagram-cl"></i></a></li>
								</ul>
							</div>
						</div>
						
					</div>
					
					<!-- Row Start -->
					<div class="row">
						<div class="col-md-12">
							<div class="copyright text-center">
								<p>&copy; Copyright 2018 <a href="{% url 'home' %}">Julio Martínez</a>. All rights reserved.</p>
							</div>
							{# V. 2.0.0 #}
						</div>
					</div>
					
				</div>
			</footer>
			
			<!-- =================== START JAVASCRIPT ================== -->
			<!-- Jquery js-->
			<script src="{% static "assets/js/jquery.min.js" %}"></script>
			
			<!-- Bootstrap js-->
			<script src="{% static "assets/plugins/bootstrap/js/bootstrap.min.js" %}"></script>
			
			<!-- Bootsnav js-->
			<script src="{% static "assets/plugins/bootstrap/js/bootsnav.js" %}"></script>
			
			<!-- Slick Slider js-->
			<script src="{% static "assets/plugins/slick-slider/slick.js" %}"></script>
			
			<!-- Custom Js -->
			<script src="{% static "assets/js/custom.js" %}"></script>
			
			<script src="{% static "assets/js/main.js" %}"></script>


			{% block scripts %}
				
			{% endblock scripts %}
		</body>
	</html>

tuexperto/templates/components/error_404.html
{% extends "components/base.html" %}
{% block content %}
	<section>
		<div class="container">
			<div class="error-page padd-top-30 padd-bot-30">
				<h1 class="mrg-top-15 mrg-bot-0 cl-danger font-250 font-bold">404</h1>
				<p>La página que buscas no existe. </p>
				<a href="{% url 'home' %}" class="btn theme-btn-trans mrg-top-20">Ir a la página principal</a>
			</div>
		</div>
	</section>
{% endblock content %}

tuexperto/templates/components/error_500.html
{% extends "components/base.html" %}
{% block content %}
	<section>
		<div class="container">
			<div class="error-page padd-top-30 padd-bot-30">
				<h1 class="mrg-top-15 mrg-bot-0 cl-danger font-250 font-bold">500</h1>
				<p>La página que buscas no existe. </p>
				<a href="{% url 'home' %}" class="btn theme-btn-trans mrg-top-20">Ir a la página principal</a>
			</div>
		</div>
	</section>
{% endblock content %}

tuexperto/templates/components/messages.html
{% if user.is_authenticated and user.is_superuser %}
	{% if messages %}
		<div class="col-md-12 col-sm-12">
			<div class="alert-group">
				{% for message in messages %}
					{% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
						<div class="alert alert-success alert-dismissable">
							<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
							{{message}}
						</div>
					{% endif %}
					{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
						<div class="alert alert-danger alert-dismissable">
							<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
							{{message}}
						</div>
					{% endif %}
				{% endfor %}
			</div>
		</div>
	{% endif %}
{% endif %}

tuexperto/templates/components/modal.html
<!-- Apply Job Popup -->
<div class="modal fade" id="apply-job" tabindex="-1" role="dialog" aria-labelledby="myModalLabel2" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content" id="myModalLabel2">
			<div class="modal-body">
				<div class="text-center">
					<img src="assets/img/logo.png" class="img-responsive" alt="">
					<h4 class="mrg-0">Front End Designer</h4>
					<span> 2708 Scenic Way, Sutter</span>
				</div>
				
				<form>
					<div class="form-group">
						<label>Name</label>
						<input type="text" class="form-control" placeholder="Name">
					</div>
					<div class="form-group">
						<label>Email</label>
						<input type="email" class="form-control" placeholder="Email">
					</div>
					
					<div class="form-group">
						<label>Phone</label>
						<input type="text" class="form-control" placeholder="Phone">
					</div>
					<div class="form-group">
						<label>Upload CV</label>
						<div class="custom-file-upload">
							<input type="file" id="file" name="myfiles[]" multiple />
						</div>
					</div>
					
					<div class="form-group">
						<textarea class="form-control height-120" placeholder="Pase CV"></textarea>
					</div>
					<div class="form-group text-center">
						<button type="button" class="btn theme-btn btn-m">Save & Apply</button>
					</div>
					
				</form>
				
			</div>
		</div>
	</div>
</div>
<!-- Apply Job Popup -->

tuexperto/templates/components/navbar.html
{% load static %} {% url 'home' as home%} {% url 'contact' as contact%}
<!-- ======================= Start Navigation ===================== -->
<nav class="navbar navbar-default navbar-mobile navbar-fixed bootsnav">
    <div class="container">
        <!-- Start Logo Header Navigation -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">
                <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">
                <img src="{% static 'logo.jpg' %}" class="logo logo-display" alt="">
                <img src="{% static 'logo.jpg' %}" class="logo logo-scrolled" alt="">
            </a>
        </div>
        <!-- End Logo Header Navigation -->
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar-menu">
            <ul class="nav navbar-nav navbar-left" data-in="fadeInDown" data-out="fadeOutUp">
                <li class="{% if request.path == home %}active{% endif %}"><a href="{{home}}">Inicio</a></li>
                {% for page in pages %} {% if page.show_in_navbar %}
                <li class="{% if request.path == page.slug %}active{% endif %}"><a href="{% url 'post' page.slug %}">{{page.title|title}}</a></li>
                {% endif %} {% endfor %} {% if categories %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Categorías</a>
                    <ul class="dropdown-menu animated fadeOutUp">
                        {% for category in categories %}
                        <li class="dropdown"><a href="{% url 'category' category.slug %}" class="dropdown-toggle" data-toggle="dropdown">{{category.title|capfirst}}</a> {% if category.subcategory_set.all %}
                            <ul class="dropdown-menu">
                                {% for subcategory in category.subcategory_set.all %}
                                <li><a href="{% url 'subcategory' category=category.slug slug=subcategory.slug %}">{{ subcategory.subcategory }}</a>
                                </li>
                                {% endfor %}
                            </ul>
                            {% endif %}
                        </li>
                        {% endfor %}
                    </ul>
                </li>
                {% endif %}
                <li class="{% if request.path == contact %}active{% endif %}"><a href="{{contact}}">Contáctanos</a></li>
                {% if user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <i class="fa fa-user"></i> {{user.username|title}}
                    </a>
                    <ul class="dropdown-menu animated fadeOutUp">
                        {% if user.user_type == 'bl' or user.is_superuser or user.is_staff %}
                        <li><a href="{% url 'user_post' pt='post' %}">Entradas</a></li>
                        {% endif %} {% if user.is_staff %}
                        <li><a href="{% url 'user_post' pt='page' %}">Páginas</a></li>
                        <li><a href="{% url 'user_courses' %}">Cursos</a></li>
                        {% endif %} {% if user.is_superuser %}
                        <li><a href="{% url 'admin:index' %}">Administrador</a></li>
                        {% endif %}
                        <li><a href="{% url 'profile' user.username %}">Perfil</a></li>
                        <li><a href="{% url 'logout' %}">Cerrar sesión</a></li>
                    </ul>
                </li>
                {% endif %}
            </ul>
            <form class="navbar-form navbar-right" action="{% url 'search' %}" role="search">
                <div class="input-group input-group-sm mrg-top-10">
                    <input type="text" name="q" id="q" class="form-control" placeholder="Buscar ...">
                    <span class="input-group-btn">
                        <button class="btn btn-radius bg-primary" type="submit"><i class="ti ti-search"></i></button>
                    </span>
                </div>
                <!-- /input-group -->
            </form>
        </div>
        <!-- /.navbar-collapse -->
    </div>
</nav>
<!-- ======================= End Navigation ===================== -->

tuexperto/templates/components/title_page.html
<!-- ======================= Start Page Title ===================== -->
<div class="page-title">
    <div class="container">
        <div class="page-caption">
            {% if title_page %}
            <h2>{{title_page}}</h2>
            {% endif %} {% if breadcrumb %}
            <p>
                {% for item in breadcrumb %} {% if not forloop.last %}
                <a href="{{item.0}}" title="{{item.1|capfirst}}">{{item.1|capfirst}}</a> <i class="ti-arrow-right"></i> {% else %} {{item.1|capfirst}} {% endif %} {% endfor %}
            </p>

            {% endif %}
        </div>
    </div>
</div>
<!-- ======================= End Page Title ===================== -->